## Settings
title: c0de.works
owner: "c0deisme"
url: "https://c0de.works"
baseurl: "/"
permalink: /:year/:month/:day/:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
## email: "c0de@c0de.works"
email: ""
github: "c0deisme"
encrypted_text: false
btn_text: false
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Theme <a href='https://github.com/akiritsu/pRoJEct-NeGYa'>pRoJEct-NeGYa</a> made by <a href='https://github.com/akiritsu'>akiritsu</a>"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
plugins:
   - jemoji